# Generated by Django 3.2.5 on 2021-07-05 21:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_user_experience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='factortag',
            name='challenge_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='challenge.challengetag'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this submission', primary_key=True, serialize=False),
        ),
    ]
