# Generated by Django 3.2.5 on 2021-07-05 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience_level',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.experiencelevel'),
        ),
    ]
