# Generated by Django 3.2.5 on 2021-07-13 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20210705_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_snapshot', models.CharField(max_length=2000, verbose_name='Input Snapshot')),
                ('time', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='challenge.user')),
            ],
        ),
    ]
