# Generated by Django 3.2.5 on 2021-07-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_submissionsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorsubmission',
            name='response1',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='factorsubmission',
            name='response2',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='factorsubmission',
            name='time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
