# Generated by Django 3.2.5 on 2021-07-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20210705_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience_level',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExperienceLevel',
        ),
    ]
