# Generated by Django 3.2.5 on 2021-07-22 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_auto_20210722_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers1', models.CharField(max_length=1000, null=True)),
                ('answers2', models.CharField(max_length=1000, null=True)),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='challenge.submission')),
            ],
        ),
    ]
