# Generated by Django 3.2.5 on 2021-07-27 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_finalquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionsnapshot',
            name='box',
            field=models.CharField(max_length=2, null=True, verbose_name='Which Textarea'),
        ),
        migrations.AddField(
            model_name='submissionsnapshot',
            name='challenge_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='challenge.challengetag'),
        ),
        migrations.AlterField(
            model_name='submissionsnapshot',
            name='input_snapshot',
            field=models.CharField(max_length=2000, null=True, verbose_name='Input Snapshot'),
        ),
    ]
